from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = f'start1{CMD_INDEX}'
        self.MirrorCommand = f'mirror1{CMD_INDEX}'
        self.UnzipMirrorCommand = f'unzipmirror1{CMD_INDEX}'
        self.ZipMirrorCommand = f'zipmirror1{CMD_INDEX}'
        self.CancelMirror = f'cancel1{CMD_INDEX}'
        self.CancelAllCommand = f'cancelall{CMD_INDEX}'
        self.ListCommand = f'search1{CMD_INDEX}'
        self.SearchCommand = f'find1{CMD_INDEX}'
        self.StatusCommand = f'status1{CMD_INDEX}'
        self.AuthorizedUsersCommand = f'users{CMD_INDEX}'
        self.AuthorizeCommand = f'authorize{CMD_INDEX}'
        self.UnAuthorizeCommand = f'unauthorize{CMD_INDEX}'
        self.AddSudoCommand = f'addsudo{CMD_INDEX}'
        self.RmSudoCommand = f'rmsudo{CMD_INDEX}'
        self.PingCommand = f'ping1{CMD_INDEX}'
        self.RestartCommand = f'restart{CMD_INDEX}'
        self.StatsCommand = f'stats{CMD_INDEX}'
        self.HelpCommand = f'help1{CMD_INDEX}'
        self.LogCommand = f'log{CMD_INDEX}'
        self.SpeedCommand = f'speedtest1{CMD_INDEX}'
        self.CloneCommand = f'clone1{CMD_INDEX}'
        self.CountCommand = f'count{CMD_INDEX}'
        self.WatchCommand = f'watch1{CMD_INDEX}'
        self.ZipWatchCommand = f'zipwatch1{CMD_INDEX}'
        self.QbMirrorCommand = f'qbmirror1{CMD_INDEX}'
        self.QbUnzipMirrorCommand = f'qbunzipmirror1{CMD_INDEX}'
        self.QbZipMirrorCommand = f'qbzipmirror1{CMD_INDEX}'
        self.DeleteCommand = f'del{CMD_INDEX}'
        self.ShellCommand = f'shell{CMD_INDEX}'
        self.ExecHelpCommand = f'exechelp{CMD_INDEX}'
        self.LeechSetCommand = f'leechset{CMD_INDEX}'
        self.SetThumbCommand = f'setthumb{CMD_INDEX}'
        self.LeechCommand = f'leech1{CMD_INDEX}'
        self.UnzipLeechCommand = f'unzipleech1{CMD_INDEX}'
        self.ZipLeechCommand = f'zipleech1{CMD_INDEX}'
        self.QbLeechCommand = f'qbleech1{CMD_INDEX}'
        self.QbUnzipLeechCommand = f'qbunzipleech1{CMD_INDEX}'
        self.QbZipLeechCommand = f'qbzipleech1{CMD_INDEX}'
        self.LeechWatchCommand = f'leechwatch1{CMD_INDEX}'
        self.LeechZipWatchCommand = f'leechzipwatch1{CMD_INDEX}'
        self.RssListCommand = f'rsslist{CMD_INDEX}'
        self.RssGetCommand = f'rssget{CMD_INDEX}'
        self.RssSubCommand = f'rsssub{CMD_INDEX}'
        self.RssUnSubCommand = f'rssunsub{CMD_INDEX}'
        self.RssSettingsCommand = f'rssset{CMD_INDEX}'

BotCommands = _BotCommands()
